"""Constants for the La Marzocco integration."""

DOMAIN = "lamarzocco"

CONF_SERIAL_NUMBER = "serial_number"
CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"

DEFAULT_NAME = "lamarzocco"

ATTR_ENABLE_PREBREWING = "ENABLE_PREBREWING"
ATTR_STBY_TIMER = "STBY_TIMER"
ATTR_TON_PREBREWING_K1 = "TON_PREBREWING_K1"
ATTR_TON_PREBREWING_K2 = "TON_PREBREWING_K2"
ATTR_TON_PREBREWING_K3 = "TON_PREBREWING_K3"
ATTR_TON_PREBREWING_K4 = "TON_PREBREWING_K4"
ATTR_TOFF_PREBREWING_K1 = "TOFF_PREBREWING_K1"
ATTR_TOFF_PREBREWING_K2 = "TOFF_PREBREWING_K2"
ATTR_TOFF_PREBREWING_K3 = "TOFF_PREBREWING_K3"
ATTR_TOFF_PREBREWING_K4 = "TOFF_PREBREWING_K4"
ATTR_TSET_STEAM = "TSET_STEAM"
ATTR_TSET_COFFEE = "TSET_COFFEE"
ATTR_DOSE_K1 = "DOSE_K1"
ATTR_DOSE_K2 = "DOSE_K2"
ATTR_DOSE_K3 = "DOSE_K3"
ATTR_DOSE_K4 = "DOSE_K4"
ATTR_DOSE_K5 = "DOSE_K5"
ATTR_DOSE_TEA = "DOSE_TEA"
STATE_STATUS = "status"
DATA_TAG = "data"
STATUS_ON = "ON"
STATUS_STANDBY = "STANDBY"
MACHINE_STATUS = "MACHINE_STATUS"

STATUS_MAP = {STATUS_ON: "On", STATUS_STANDBY: "Standby"}

COMMAND_ON = {"status": "ON"}
COMMAND_STANDBY = {"status": "STANDBY"}

ATTR_MAP = {
    STATE_STATUS: "Status",
    ATTR_ENABLE_PREBREWING: "Prebrewing Enabled",
    ATTR_STBY_TIMER: "Standby Timer",
    ATTR_TON_PREBREWING_K1: "Prebrewing Time On (Key 1)",
    ATTR_TON_PREBREWING_K2: "Prebrewing Time On (Key 2)",
    ATTR_TON_PREBREWING_K3: "Prebrewing Time On (Key 3)",
    ATTR_TON_PREBREWING_K4: "Prebrewing Time On (Key 4)",
    ATTR_TOFF_PREBREWING_K1: "Prebrewing Time Off (Key 1)",
    ATTR_TOFF_PREBREWING_K2: "Prebrewing Time Off (Key 2)",
    ATTR_TOFF_PREBREWING_K3: "Prebrewing Time Off (Key 3)",
    ATTR_TOFF_PREBREWING_K4: "Prebrewing Time Off (Key 4)",
    ATTR_TSET_STEAM: "Steam Temperature",
    ATTR_TSET_COFFEE: "Coffee Temperature",
    ATTR_DOSE_K1: "Dose (Key 1)",
    ATTR_DOSE_K2: "Dose (Key 2)",
    ATTR_DOSE_K3: "Dose (Key 3)",
    ATTR_DOSE_K4: "Dose (Key 4)",
    ATTR_DOSE_K5: "Dose (Key 5)",
    ATTR_DOSE_TEA: "Dose (Tea)",
}