"""Constants for the La Marzocco integration."""

from lmdirect.const import MODEL_NAME
from lmdirect.msgs import *

DOMAIN = "lamarzocco"

"""Set polling interval at 20s."""
POLLING_INTERVAL = 30

"""Configuration parameters"""
CONF_SERIAL_NUMBER = "serial_number"
CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"
CONF_KEY = "key"
CONF_MACHINE_NAME = "machine_name"
CONF_MODEL_NAME = "model_name"

DEFAULT_PORT = 1774

DEFAULT_NAME = "Espresso Machine"

SCHEMA = "schema"
MODELS_SUPPORTED = "supported"
FUNC = "func"

SUPPORTED = "supported"
MODELS = [MODEL_GS3_AV, MODEL_GS3_MP, MODEL_LM]

"""List of attributes for each entity based on model."""
ATTR_MAP_MAIN_GS3_AV = [
    DATE_RECEIVED,
    MACHINE_NAME,
    MODEL_NAME,
    UPDATE_AVAILABLE,
    POWER_MYSTERY,
    HEATING_STATE,
    KEY_ACTIVE,
    CURRENT_PULSE_COUNT,
    (DOSE, "k1"),
    (DOSE, "k2"),
    (DOSE, "k3"),
    (DOSE, "k4"),
    (DOSE, "k5"),
    DOSE_HOT_WATER,
    COFFEE_HEATING_ELEMENT_HOURS,
    STEAM_HEATING_ELEMENT_HOURS,
    DAYS_SINCE_BUILT,
    WATER_ON_SECONDS,
    FRONT_PANEL_DISPLAY,
    MYSTERY_1,
    MYSTERY_2
]

ATTR_MAP_MAIN_GS3_MP = [
    DATE_RECEIVED,
    MACHINE_NAME,
    MODEL_NAME,
    UPDATE_AVAILABLE,
    POWER_MYSTERY,
    HEATING_STATE,
    COFFEE_HEATING_ELEMENT_HOURS,
    STEAM_HEATING_ELEMENT_HOURS,
    DAYS_SINCE_BUILT,
    WATER_ON_SECONDS,
    FRONT_PANEL_DISPLAY,
]

ATTR_MAP_MAIN_LM = [
    DATE_RECEIVED,
    MACHINE_NAME,
    MODEL_NAME,
    UPDATE_AVAILABLE,
    POWER_MYSTERY,
    HEATING_STATE,
    DAYS_SINCE_BUILT,
    WATER_ON_SECONDS,
]

ATTR_MAP_STEAM_BOILER_ENABLE = [
    DATE_RECEIVED,
]

ATTR_MAP_PREBREW_GS3_AV = [
    DATE_RECEIVED,
    (PREBREWING, TON, "k1"),
    (PREBREWING, TON, "k2"),
    (PREBREWING, TON, "k3"),
    (PREBREWING, TON, "k4"),
    (PREBREWING, TOFF, "k1"),
    (PREBREWING, TOFF, "k2"),
    (PREBREWING, TOFF, "k3"),
    (PREBREWING, TOFF, "k4"),
]

ATTR_MAP_PREINFUSION_GS3_AV = [
    DATE_RECEIVED,
    (PREINFUSION, "k1"),
    (PREINFUSION, "k2"),
    (PREINFUSION, "k3"),
    (PREINFUSION, "k4"),
]

ATTR_MAP_PREINFUSION_LM = [
    DATE_RECEIVED,
    (PREINFUSION, "k1"),
]

ATTR_MAP_PREBREW_LM = [
    DATE_RECEIVED,
    (PREBREWING, TON, "k1"),
    (PREBREWING, TOFF, "k1"),
]

ATTR_MAP_COFFEE = [
    DATE_RECEIVED,
    COFFEE_HEATING_ELEMENT_HOURS,
]

ATTR_MAP_STEAM = [
    DATE_RECEIVED,
    STEAM_HEATING_ELEMENT_HOURS,
]

ATTR_MAP_AUTO_ON_OFF = [
    DATE_RECEIVED,
    (SUN, AUTO),
    (SUN, ON, TIME),
    (SUN, OFF, TIME),
    (MON, AUTO),
    (MON, ON, TIME),
    (MON, OFF, TIME),
    (TUE, AUTO),
    (TUE, ON, TIME),
    (TUE, OFF, TIME),
    (WED, AUTO),
    (WED, ON, TIME),
    (WED, OFF, TIME),
    (THU, AUTO),
    (THU, ON, TIME),
    (THU, OFF, TIME),
    (FRI, AUTO),
    (FRI, ON, TIME),
    (FRI, OFF, TIME),
    (SAT, AUTO),
    (SAT, ON, TIME),
    (SAT, OFF, TIME),
]

ATTR_MAP_DRINK_STATS_GS3_AV = [
    DATE_RECEIVED,
    (DRINKS, "k1"),
    (DRINKS, "k2"),
    (DRINKS, "k3"),
    (DRINKS, "k4"),
    CONTINUOUS,
    TOTAL_FLUSHING,
    DRINKS_HOT_WATER,
    HOT_WATER,
    MACHINE_RUNNING_SECONDS,
    PUMP_ON_SECONDS,
    DRINK_MYSTERY,
    TOTAL_COFFEE,
    TOTAL_COFFEE_ACTIVATIONS,
    HOT_WATER_2,
]

ATTR_MAP_DRINK_STATS_GS3_MP_LM = [
    DATE_RECEIVED,
    (DRINKS, "k1"),
    CONTINUOUS,
    TOTAL_FLUSHING,
    DRINKS_HOT_WATER,
    HOT_WATER,
    MACHINE_RUNNING_SECONDS,
    PUMP_ON_SECONDS,
    DRINK_MYSTERY,
    TOTAL_COFFEE,
    TOTAL_COFFEE_ACTIVATIONS,
    HOT_WATER_2,
]

ATTR_MAP_WATER_RESERVOIR = [
    WATER_RESERVOIR_CONTACT
]

ENTITY_TAG = "tag"
ENTITY_TEMP_TAG = "temp_tag"
ENTITY_TSET_TAG = "tset_tag"
ENTITY_NAME = "name"
ENTITY_MAP = "map"
ENTITY_TYPE = "type"
ENTITY_ICON = "icon"
ENTITY_FUNC = "func"
ENTITY_CLASS = "class"
ENTITY_UNITS = "units"

PLATFORM = "platform"
PLATFORM_SENSOR = "sensor"
PLATFORM_SWITCH = "switch"

"""Service call names."""
SERVICE_SET_AUTO_ON_OFF_ENABLE = "set_auto_on_off_enable"
SERVICE_SET_AUTO_ON_OFF_TIMES = "set_auto_on_off_times"
SERVICE_SET_DOSE = "set_dose"
SERVICE_SET_DOSE_HOT_WATER = "set_dose_hot_water"
SERVICE_SET_PREBREW_TIMES = "set_prebrew_times"
SERVICE_SET_PREINFUSION_TIME = "set_preinfusion_time"
