"""Constants for the La Marzocco integration."""

DOMAIN = "lamarzocco"

CONF_SERIAL_NUMBER = "serial_number"
CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"

DEFAULT_NAME = "Espresso Machine"

ATTRIBUTION = "Data from La Marzocco"

COMMAND_ON = {"status": "ON"}
COMMAND_STANDBY = {"status": "STANDBY"}

TEMP_KEYS = ["TSET", "TEMP"]

DATA_TAG = "data"

STATUS_RECEIVED = "RECEIVED"
STATUS_MACHINE_STATUS = "MACHINE_STATUS"
STATUS_TEMP_STEAM = "TEMP_STEAM"
STATUS_TEMP_COFFEE = "TEMP_COFFEE"
STATUS_TSET_STEAM = "TSET_STEAM"
STATUS_TSET_COFFEE = "TSET_COFFEE"
STATUS_DOSE_K1 = "DOSE_K1"
STATUS_DOSE_K2 = "DOSE_K2"
STATUS_DOSE_K3 = "DOSE_K3"
STATUS_DOSE_K4 = "DOSE_K4"
STATUS_DOSE_K5 = "DOSE_K5"
STATUS_DOSE_TEA = "DOSE_TEA"
STATUS_ENABLE_PREBREWING = "ENABLE_PREBREWING"
STATUS_TON_PREBREWING_K1 = "TON_PREBREWING_K1"
STATUS_TON_PREBREWING_K2 = "TON_PREBREWING_K2"
STATUS_TON_PREBREWING_K3 = "TON_PREBREWING_K3"
STATUS_TON_PREBREWING_K4 = "TON_PREBREWING_K4"
STATUS_TOFF_PREBREWING_K1 = "TOFF_PREBREWING_K1"
STATUS_TOFF_PREBREWING_K2 = "TOFF_PREBREWING_K2"
STATUS_TOFF_PREBREWING_K3 = "TOFF_PREBREWING_K3"
STATUS_TOFF_PREBREWING_K4 = "TOFF_PREBREWING_K4"

ATTR_STATUS_MAP = {
    STATUS_RECEIVED: "date_received",
    STATUS_TEMP_STEAM: "steam_temp",
    STATUS_TEMP_COFFEE: "coffee_temp",
    STATUS_TSET_STEAM: "steam_temp_setting",
    STATUS_TSET_COFFEE: "coffee_temp_setting",
    STATUS_DOSE_K1: "dose_k1",
    STATUS_DOSE_K2: "dose_k2",
    STATUS_DOSE_K3: "dose_k3",
    STATUS_DOSE_K4: "dose_k4",
    STATUS_DOSE_K5: "dose_k5",
    STATUS_DOSE_TEA: "dose_tea",
    STATUS_ENABLE_PREBREWING: "prebrewing_enabled",
    STATUS_TON_PREBREWING_K1: "prebrewing_ton_k1",
    STATUS_TON_PREBREWING_K2: "prebrewing_ton_k2",
    STATUS_TON_PREBREWING_K3: "prebrewing_ton_k3",
    STATUS_TON_PREBREWING_K4: "prebrewing_ton_k4",
    STATUS_TOFF_PREBREWING_K1: "prebrewing_toff_k1",
    STATUS_TOFF_PREBREWING_K2: "prebrewing_toff_k2",
    STATUS_TOFF_PREBREWING_K3: "prebrewing_toff_k3",
    STATUS_TOFF_PREBREWING_K4: "prebrewing_toff_k4",
}

# Services
SERVICE_SET_COFFEE_TEMP = "set_coffee_temp"
SERVICE_SET_STEAM_TEMP = "set_steam_temp"
SERVICE_SET_PREBREWING_ENABLE = "set_prebrewing_enable"
